services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ChristianEssl\Impersonate\:
        resource: '../Classes/*'

    ChristianEssl\Impersonate\Listener\RecordListRecordActionsListener:
        tags:
            -   name: event.listener
                identifier: 'tx-impersonate-modify-record-list-record-actions'
                event: TYPO3\CMS\Backend\RecordList\Event\ModifyRecordListRecordActionsEvent

    ChristianEssl\Impersonate\Controller\FrontendLoginController:
        public: true
